# Generated by Django 5.2.10 on 2026-02-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='shape',
            field=models.CharField(choices=[('cube', 'Cube'), ('sphere', 'Sphere'), ('pyramid', 'Pyramid')], default='cube', max_length=20),
        ),
    ]
